### ISSUE TITLE
Exercise 9 - adding zero?

### ISSUE THREAD

**Issue by WadeWaldron** [lightbend-training/course-management-tools#18]
Original Issue: https://github.com/typesafe-training/fast-track-akka-scala/issues/14
Originally reported by @alejandrolujan

Why do we have this in CoffeeHouse.scala:

guestBook += guest -> (guestBook(guest) + 0)

instead of this:

guestBook += guest -> guestBook(guest)

?

**Comment by eloots** [comment]
Think this issue belongs in https://github.com/lightbend-training/FTTAS-fast-track-akka-scala

**Comment by WadeWaldron** [comment]
Bah. You are right. Oops.
