### ISSUE TITLE
Revert to initial state of exercise

### ISSUE THREAD

**Issue by michaelpnash** [lightbend-training/course-management-tools#29]
Once pullSolution has been used, there is no way to get back to the *initial* state of the exercise, it seems

**Comment by eloots** [comment]
Depends on the definition of _initial_ state:

- The state of the exercise as it was just before running the `pullSolution` command
- The state of the exercise as it was right after running the `nextExercise` command while being on the previous exercise (= _fromState_). Two cases should be distinguished:
   - _fromState_ is the state in which the previous exercise was _without_ having pulled the 'standard' solution => in essence this is equivalent to the first bullet item.
   - _fromState_ is the state in the previous exercise _with_ the standard solution pulled.

**Comment by eloots** [comment]
@michaelpnash Does my reply suffice as a clarification?

**Comment by WadeWaldron** [comment]
The way I have done this is to go to the previous exercise, then pull solution, then go forward again. This (I believe) puts you in a state where the exercise needs to be completed.

Alternatively you can use the snapshot functionality.

**Comment by eloots** [comment]
I misunderstood the issue; my fault... indeed, this is the way to do it.

**Comment by michaelpnash** [comment]
Eric, Wade: Indeed that's what I meant, if a student did a pullSolution, then decided then wanted to try the exercise on their own.

That workaround should be fine, perhaps a mention in the doc...I'll PR one.

Thx!
