### ISSUE TITLE
validateStudentRepo.sh doesn't validate first exercise in a repo

### ISSUE THREAD

**Issue by eloots** [lightbend-training/course-management-tools#34]
Cause is that, after initialisation, `validataStudentRepo.sh` moves to the next exercise and _then_ runs the test on the selected exercise. Hence, the tests on the first exercise on a repo are never run.

**Comment by WadeWaldron** [comment]
I believe this is because most of our courses have a "zero" exercise. So this basically ignores that exercise and moves to the actual first exercise.

That might not be desirable though.

**Comment by eloots** [comment]
Resolved by PR #36
