### ISSUE TITLE
Course Master validation

### ISSUE THREAD

**Issue by eloots** [lightbend-training/course-management-tools#43]
Currently, there's no checking of the structure of a course master, e.g. 'is there a .courseName file in the project root folder?', 'Do all exercise folders have a README.md file in src/test/resources?', 'do the README.md files have the minimally expected structure?', etc...

**Comment by WadeWaldron** [comment]
What is the consequence right now if those things are missing? Does the process crash or does it produce a broken repo?

**Comment by eloots** [comment]
This issue should have been closed quite some time ago as it has been implemented as an option of the `masterAdm` command (see #55). CC @WadeWaldron
