### ISSUE TITLE
Allow for leaving out trailing underscore and text for exercise projects

### ISSUE THREAD

**Issue by ennru** [lightbend-training/course-management-tools#67]
Leaving out the trailing underscore should work. However, I would allow it only if there’s no trailing part on the name after the 3 digits. E.g. `step_003` is ok. So is `step_003_bla`, but `step_003bla` isn’t.

**Comment by eloots** [comment]
Yes — that’s exactly what I meant. 

Verstuurd vanaf mijn iPhone

**Comment by eloots** [comment]
It was decided that allowing project names with no description after the sequence number is not very useful in practice. Closing
